[monitors]
hdmi-0 = 3840x2160               # 4K primary
dp-0 = 1280x1024               # left screen
dp-2 = 1024x768                # no-EDID adapter, modeline 1024x768_60
dp-4 = 1680x1050               # no-EDID Dell, modeline 1680x1050R @59.88

[defaults]
monitor = DP-4
projection-monitor = HDMI-0
layout = full

[windows]
snapchat = DP-4:0,0:50%,100%
groupme = DP-4:50%,0:50%,100%
stephen studio = HDMI-0:0,0:50%,100%
daw = HDMI-0:50%,0:50%,100%
video = HDMI-0:0,0:50%,50%
lino assistant = HDMI-0:top-center:200x200
lino chat = HDMI-0:center:50%,60%

